### PR TITLE
UBERF-4631: Fix issue when link preview in activity displayed as #undefined

### LINKED ISSUE #4188: Link preview in activity displayed as #undefined undefined
See <https://front.hc.engineering/workbench/platform/tracker/UBERF-4630>

**Summary**

Shown “#undefined undefined“ instead of MR id and description text in the issue comment for the GitHub link

**Steps to reproduce:**

1. Login to platform
2. Created an issue
3. Add comment to the issue with the Github link

**Actual Result**

Shown “#undefined undefined“ text in the preview example: <https://front.hc.engineering/workbench/platform/tracker/UBERF-4835>

**Expected Result**

Should be shown GitHub MR id and summary —? cc can you help with determining the expected result?

### PR DESCRIPTION
**Pull request by agrigorovich-xored**
# Contribution checklist

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svele-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

## Contributor requirements

* [x] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [x] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

File: plugins/view-resources/src/components/linkPresenters/GithubPresenter.svelte [hunk 1]
```diff
@@ -67,7 +67,11 @@
   <div class="line" style="background-color: {getPlatformColor(7, $themeStore.dark)}" />
   {#await getData(href) then data}
     <div class="flex-col">
-      <a class="fs-title mb-1" {href}>#{data.number} {data.title}</a>
+      {#if data.number !== undefined && data.title !== undefined}
+        <a class="fs-title mb-1" {href}>#{data.number} {data.title}</a>
+      {:else}
+        <a class="fs-title mb-1" {href}><LabelComponent label={view.string.ViewOnGithub}/></a>
+      {/if}
       {#if data.body}
```
Comment (ThetaDR) [inline plugins/view-resources/src/components/linkPresenters/GithubPresenter.svelte]: I think it would be better not to show this presenter at all if there is no data. Showing label instead of embedded info doesn't make sense for me, it's either data or no presenter at all

**Review by haiodo — DISMISSED** [review]

File: plugins/view-resources/src/components/linkPresenters/GithubPresenter.svelte (hunk 1 above)
Comment (haiodo) [reply plugins/view-resources/src/components/linkPresenters/GithubPresenter.svelte]: Hmps, agree.

Comment (agrigorovich-xored) [reply plugins/view-resources/src/components/linkPresenters/GithubPresenter.svelte]: Done.

**Review by ThetaDR — APPROVED** [review]

**Review by haiodo — APPROVED** [review]
