### PR TITLE
Fixed IntegrationConfigure layout

### LINKED ISSUE #7427: Choose one calendar when import google calendar
### Description of the issue

When I want to import Google Calendar, I can't choose which calendar to display on the planner. This is unfortunate because, as a student, I only need the calendar with my classes to organize my days.

### PR DESCRIPTION
**Pull request by SasLord**
1. Fixed IntegrationConfigure layout
2. The tooltip displays long links correctly
   screen-1 screen-2
   Close #7427

### CODE REVIEW

File: packages/ui/src/components/TooltipInstance.svelte [hunk 1]
```diff
@@ -264,6 +264,11 @@
   onDestroy(() => {
     hideTooltip()
   })
+
+  const isValidUrl = (url: string): boolean => {
```
Comment (haiodo) [inline packages/ui/src/components/TooltipInstance.svelte]: No, no and no

File: packages/ui/src/components/TooltipInstance.svelte [hunk 2]
```diff
@@ -370,7 +375,9 @@
     style:transform={options.transform}
     style:z-index={($modals.findIndex((t) => t.type === 'tooltip') ?? 1) + 10000}
   >
-    <Label label={$tooltip.label} params={$tooltip.props ?? {}} />
+    <span class:label-wrap={isValidUrl($tooltip.label)}>
```
Comment (haiodo) [inline packages/ui/src/components/TooltipInstance.svelte]: No, no and no

**Review by haiodo — CHANGES_REQUESTED** [review]

**Review by haiodo — APPROVED** [review]
