### PR TITLE
Fix workspace creation

### LINKED ISSUE #696: Fix workspace creation

### PR DESCRIPTION
**Pull request by sumboid**
Resolves #696
Also task, lead and recruit migrations have been removed

### CODE REVIEW

File: models/all/src/migration.ts [hunk 1]
```diff
@@ -17,17 +17,11 @@ import { MigrateOperation } from '@anticrm/model'
 
 // Import migrate operations.
 import { coreOperation } from '@anticrm/model-core'
-import { taskOperation } from '@anticrm/model-task'
```
Comment (haiodo) [inline models/all/src/migration.ts]: I recommend to not remove them, since I assume a lot of times we will need them back.

Comment (sumboid) [reply models/all/src/migration.ts]: Done

**Review by aplatoff — APPROVED** [review]
