### PR TITLE
Update DatePicker. Add and update presenters. Fix Activity layout.

### LINKED ISSUE #1148: Allow standard right-click and middle-click actions for Candidates list
It'd be good to be able to naturally open multiple candidate pages in separate tabs from the Candidates list. It's hard to do now, as only left click/tap works on candidate names, and it opens the candidate page in the same tab. It would be great to have

- middle click (Cmd+tap) support, which would open the candidate page in a new tab
- right-click support, which would open a standard browser right-click menu for a URL with options like 'Open in new tab', 'Copy link', etc.

### LINKED ISSUE #1158: Fix paddings for few created child objects

### LINKED ISSUE #1159: Date With Time chooser

### PR DESCRIPTION
**Pull request by SasLord**
Presenters to links (fixes #1148)
Fix paddings for few created child objects (fixes #1158)
Update DatePicker. Add DateTimePresenter. (fixes #1159)

### CODE REVIEW

File: plugins/contact-resources/src/components/OrganizationPresenter.svelte [hunk 1]
```diff
@@ -28,8 +28,13 @@
 </script>
 
 {#if value}
-  <div class="flex-presenter" class:inline-presenter={inline} on:click={onClick}>
+  <a
+    class="flex-presenter"
+    class:inline-presenter={inline}
+    href="#{encodeURIComponent([view.component.EditDoc, value._id, value._class].join('|'))}"
```
Comment (haiodo) [inline plugins/contact-resources/src/components/OrganizationPresenter.svelte:34]: It looks absolutely weird.

**Review by haiodo — APPROVED** [review]
