### PR TITLE
Chunter: file browser additional fixes

### LINKED ISSUE #1503: Chunter: Browse not fit
Screenshot 2022-04-24 at 01 04 54

### PR DESCRIPTION
**Pull request by ksilobait**
Signed-off-by: Ruslan Izhitsky [ruslan.izhitskiy@xored.com](mailto:ruslan.izhitskiy@xored.com) Related issue: https://github.com/hcengineering/anticrm/issues/1407 Closes: https://github.com/hcengineering/anticrm/issues/1503

### CODE REVIEW

File: models/chunter/src/index.ts [hunk 1]
```diff
@@ -334,7 +334,10 @@ export function createModel (builder: Builder): void {
             id: 'fileBrowser',
             label: attachment.string.FileBrowser,
             icon: attachment.icon.FileBrowser,
-            component: attachment.component.FileBrowser
+            component: attachment.component.FileBrowser,
+            componentProps: {
+              requestedSpaceClasses: [chunter.class.Channel]
```
Comment (BykhovDenis) [inline models/chunter/src/index.ts]: Please add DM space too

File: packages/presentation/src/components/SpacesMultiPopup.svelte [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+  import presentation from '..'
+  import SpaceInfo from './SpaceInfo.svelte';
+
+  export let selected: Ref<Space> | undefined
+  export let _classes: Ref<Class<Space>>[] = []
+  export let allowDeselect: boolean = false
+  export let titleDeselect: IntlString | undefined = undefined
+  export let placeholder: IntlString = presentation.string.Search
+  export let selectedSpaces: Ref<Space>[] = []
+  export let ignoreSpaces: Ref<Space>[] = []
```
Comment (BykhovDenis) [inline packages/presentation/src/components/SpacesMultiPopup.svelte]: Why we need it here?

File: packages/presentation/src/components/SpacesMultiPopup.svelte [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+  const query = createQuery()
+  $: query.query<Space>(
+    core.class.Space,
+    {
+      name: { $like: '%' + search + '%' },
+      _class: { $in: _classes },
+      _id: { $nin: ignoreSpaces }
+    },
+    result => {
+      objects = result
```
Comment (BykhovDenis) [inline packages/presentation/src/components/SpacesMultiPopup.svelte]: Let's filter private spaces when user is not joined

**Review by BykhovDenis — CHANGES_REQUESTED** [review]

File: packages/presentation/src/components/SpacesMultiPopup.svelte [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+  const dispatch = createEventDispatcher()
+  const query = createQuery()
+  const myAccId = getCurrentAccount()._id
+
+  $: query.query<Space>(
+    core.class.Space,
+    {
+      name: { $like: '%' + searchQuery + '%' },
+      _class: { $in: _classes },
+      private: false,
```
Comment (BykhovDenis) [inline packages/presentation/src/components/SpacesMultiPopup.svelte]: It's extra, you filter it later

File: packages/presentation/src/components/SpacesMultiPopup.svelte [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+      {#each shownSpaces as space}
+        <button class="menu-item" on:click={() => {
+          checkSelected(space)
+        }}>
+          <div class="check pointer-events-none">
+            <CheckBox checked={isSelected(space)} primary />
+          </div>
+          <SpaceInfo size={'medium'} value={space} />
+          {#if space.archived}
+            &nbsp;<Label label={presentation.string.Archived}/>
```
Comment (BykhovDenis) [inline packages/presentation/src/components/SpacesMultiPopup.svelte]: I think better add it in SpaceInfo

**Review by BykhovDenis — CHANGES_REQUESTED** [review]

**Review by BykhovDenis — APPROVED** [review]
