### PR TITLE
Fix tags popup and Applicant Labels

### LINKED ISSUE #1940: Platform: Tags, collapse on tag selection

### PR DESCRIPTION
**Pull request by haiodo**
# Contribution checklist

## Brief description

Fix tags/skills popup. Add sorting and fix category auto closing.

image

## Checklist

* [x] - Does the code work? Check whether function and logic are correct.
* [x] - Does Changelog.md is updated with changes?
* [x] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [x] - Does new code is well documented ?

## Related issues

Closes #1940

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

### CODE REVIEW

File: plugins/view-resources/src/components/EditDoc.svelte [hunk 1]
```diff
@@ -256,12 +257,13 @@
...
           ignoreKeys = ev.detail.ignoreKeys
           ignoreMixins = new Set(ev.detail.ignoreMixins)
+          allowedCollections = ev.detail.allowedCollections ?? []
           getMixins(parentClass, object)
           updateKeys()
         }}
       />
     {/if}
-    {#each collectionEditors as collection}
+    {#each collectionEditors.filter((it) => !allowedCollections.includes(it.key.key)) as collection}
```
Comment (BykhovDenis) [inline plugins/view-resources/src/components/EditDoc.svelte:266]: May be better place for it in `utils/collectionsFilter`?

**Review by BykhovDenis — APPROVED** [review]

File: plugins/view-resources/src/components/EditDoc.svelte (hunk 1 above)
Comment (haiodo) [reply plugins/view-resources/src/components/EditDoc.svelte:266]: Not sure, let it be for now.
