### PR TITLE
UBERF-8005: Add tests to tracker projects, fix failed tests

### LINKED ISSUE #6453: Test: Star/Unstar/Unarchive/Leave project
**Star/Unstar steps:**

1. Log into the system
2. Create project if not exist
3. Click Button “Star“ of project in Left menu
4. Check that project is removed from “YOURS PROJECTS“ and add to “STARRED”
5. Click Button “Unstar“ of project in Left menu in block “STARRED“
6. Check that project is removed from “STARRED“ and add to “YOURS PROJECT”

 **Unarchive steps:**

1. Log into the system
2. Create project if not exist
3. Click Button “Archive“ of project in Left menu
4. Check that project is removed from “YOURS PROJECTS“
5. Open All projects
6. Find project end check that project named [Project name] (archived)
7. Right click on project and click “Unarchived”
8. Check that project name in grid is [Project name]
9. Check that project add to LeftMenu in YOURS PROJECTS

 **Leave Own Project steps:**

1. Log into the system
2. Create project if not exist
3. Click Button “Leave“ of project in Left menu
4. Check that project is removed from “YOURS PROJECTS“
5. Click Button “Unstar“ of project in Left menu in block “STARRED“
6. Check that project is removed from “STARRED“ and add to “YOURS PROJECT”
7. Open All projects
8. Check that project is not exist in grid

Additionaly need to do:

* Make old tests independent of quantity and order of runs

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQzNDg4OGFjY2U3NzU1MjYyZmM5NDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.fNkVnWIM_Z6nzbKvIT49kkO47cvh_2Y7t0zP5y8j_2k">Huly&reg;: <b>UBERF-8005</b></a></sub>

### PR DESCRIPTION
**Pull request by kakRostropovich**
**Pull Request Requirements:**

* Add tests of star/unstar/unarchive/leave/join actions to tracker
* Make old tests independent of quantity and order of runs

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQzNGMxY2FjY2U3NzU1MjYyZmM5OGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.WQcgaNM-LrxfGu-3QwJBT8_oADXRchymdY8FG2qN-6Q">Huly&reg;: <b>UBERF-8008</b></a></sub>

### CODE REVIEW

File: tests/sanity/tests/model/tracker/all-projects-page.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+  async unarchiveProject (title: string): Promise<void> {
+    const projectRow = this.page.locator('.antiTable-body__row', { has: this.page.locator(`td:has-text("${title}")`) })
+    await projectRow.click({ button: 'right' })
+    await this.page.locator('.popup button:has-text("Unarchive")').click()
+    await this.page.locator('.popup button:has-text("Ok")').click()
+  }
+
+  async checkProjecInTableIsNotArchived (title: string): Promise<void> {
+    await this.page.waitForTimeout(3000)
```
Comment (haiodo) [inline tests/sanity/tests/model/tracker/all-projects-page.ts]: Could we make it work without timeout?

Comment (kakRostropovich) [reply tests/sanity/tests/model/tracker/all-projects-page.ts]: yes, you're right, I'll update it

Comment (kakRostropovich) [reply tests/sanity/tests/model/tracker/all-projects-page.ts]: done

**Review by haiodo — APPROVED** [review]
