### PR TITLE
Calendar Week view and some fixes

### LINKED ISSUE #1219: Calendar Week View

### PR DESCRIPTION
**Pull request by haiodo**
Closes #1219

image

Signed-off-by: Andrey Sobolev [haiodo@gmail.com](mailto:haiodo@gmail.com)

### CODE REVIEW

File: packages/ui/src/components/calendar/WeekCalendar.svelte [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+  function onSelect (date: Date) {
+    value = date
+    dispatch('change', value)
+  }
+</script>
+
+<table class="antiTable">
+  <thead class="scroller-thead">
+    <tr class="scroller-thead__tr">
+      <th>Hours</th>
```
Comment (BykhovDenis) [inline packages/ui/src/components/calendar/WeekCalendar.svelte:40]: We need I18n it

**Review by BykhovDenis — APPROVED** [review]
