### PR TITLE
Fix PDF viewer close with Cross mark

### LINKED ISSUE #912: Закрывать предпросмотр PDF не только через Escape
Сейчас можно закрыть предпросмотр PDF только через Escape. Стрелка назад не работает

### PR DESCRIPTION
**Pull request by haiodo**
Fix PDF viewer close with Cross mark

Closes #912

Signed-off-by: Andrey Sobolev [haiodo@gmail.com](mailto:haiodo@gmail.com)

### CODE REVIEW

File: packages/presentation/src/components/PDFViewer.svelte [hunk 1]
```diff
@@ -67,7 +66,7 @@
   .pdfviewer-container {
     display: flex;
     flex-direction: column;
-    width: 45rem;
+    width: 55rem;
```
Comment (BykhovDenis) [inline packages/presentation/src/components/PDFViewer.svelte:69]: Why 55? I think we need min-width and max-width

**Review by BykhovDenis — APPROVED** [review]

File: packages/presentation/src/components/PDFViewer.svelte (hunk 1 above)
Comment (haiodo) [reply packages/presentation/src/components/PDFViewer.svelte:69]: Probable.
