### PR TITLE
UBERF-7753: Change auth approach for providers

### LINKED ISSUE #6203: OAuth login fails for branded urls on prod
<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFhMWE3NWRhNTY1NDI5ZDY2MjYyNTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.D0wBFTkMh4E-wqGEIlhreKjLsxvk_nwBLb7bFuDTS-I">Huly&reg;: <b>UBERF-7753</b></a></sub>

### PR DESCRIPTION
**Pull request by lexiv0re**
* Updates auth approach for providers to pass token directly instead of setting a session cookie to account url

Related to: https://front.hc.engineering/workbench/platform/tracker/UBERF-7753
Closes: https://github.com/hcengineering/platform/issues/6203

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmFjYzkzM2RhNTY1NDI5ZDY2MjZhYzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.PaNTg8-3ffFKiBPUwz61z_SK8LmmgxKOgesRu3QATK4">Huly&reg;: <b>UBERF-7785</b></a></sub>

### CODE REVIEW

File: pods/authProviders/src/index.ts [hunk 1]
```diff
@@ -43,10 +42,8 @@ export function registerProviders (
   }
 
   app.keys = [serverSecret]
-  app.use(session({}, app))
```
Comment (aonnikov) [inline pods/authProviders/src/index.ts:46]: I receive the following error when trying to go with token:
```
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
2024-08-04 23:24:31       at vZt.logIn (/usr/src/app/bundle.js:50668:7769)
2024-08-04 23:24:31       at Yne.login.Yne.logIn (/usr/src/app/bundle.js:50668:2141)
2024-08-04 23:24:31       at m.success (/usr/src/app/bundle.js:50668:5420)
2024-08-04 23:24:31       at n (/usr/src/app/bundle.js:50668:52137)
2024-08-04 23:24:31       at /usr/src/app/bundle.js:50668:53242
```
I support this is because session/passport session

Comment (lexiv0re) [reply pods/authProviders/src/index.ts:46]: Ok, thanks. I was not sure if it's required even if don't use the session, seems it is. Will get it back/

Comment (lexiv0re) [reply pods/authProviders/src/index.ts:46]: Got it back.

Comment (aonnikov) [reply pods/authProviders/src/index.ts:46]: Works fine now

**Review by aonnikov — APPROVED** [review]

**Review by BykhovDenis — APPROVED** [review]
