### PR TITLE
Workspace Versioning

### LINKED ISSUE #857: Support Workspace versioning.
Provider Front Version and prevent it to work with workspaces with wrong version.

'Server is under maintenance' should be shown.

### PR DESCRIPTION
**Pull request by haiodo**
1. Version in models/all - should be manually updated.
2. Version is integrated into front bundle.js using esbuild.
3. rush model-version, will print current model version in workspace.

Closes #857

Screenshot 2022-01-25 at 01 29 02

Signed-off-by: Andrey Sobolev [haiodo@gmail.com](mailto:haiodo@gmail.com)

### CODE REVIEW

File: plugins/workbench-resources/src/components/WorkbenchApp.svelte [hunk 1]
```diff
@@ -39,13 +43,40 @@ async function connect(): Promise<Client | undefined> {
...
   }
+
+  try {
+    console.log('checking model version')
+    const version = await instance.findOne(core.class.Version, {})
+    console.log('Model version', version)
+
+    const requirdVersion = getMetadata(workbench.metadata.RequiredVersion)
+    if (requirdVersion !== undefined) {
+      console.log('checking min model version', requirdVersion)
```
Comment (BykhovDenis) [inline plugins/workbench-resources/src/components/WorkbenchApp.svelte:62]: Extra logs?

**Review by BykhovDenis — APPROVED** [review]

File: plugins/workbench-resources/src/components/WorkbenchApp.svelte (hunk 1 above)
Comment (haiodo) [reply plugins/workbench-resources/src/components/WorkbenchApp.svelte:62]: This is for purpose. Let it be for now.
