### PR TITLE
Tracker: Fix IssuesList selection

### LINKED ISSUE #1569: Tracker: IssuesList incorrect selection
1. `--menu-bg-select` color should be used for selected elements.
2. `selection` is not updated on mouse move.

### PR DESCRIPTION
**Pull request by agrigorovich-xored**
Closes #1569

### CODE REVIEW

File: plugins/tracker-resources/src/components/issues/IssuesList.svelte [hunk 1]
```diff
@@ -305,7 +305,7 @@
     border-bottom: 1px solid var(--theme-button-border-hovered);
 
     &.mListGridChecked {
-      background-color: var(--theme-table-bg-hover);
+      background-color: var(--menu-bg-select);
```
Comment (haiodo) [inline plugins/tracker-resources/src/components/issues/IssuesList.svelte]: For table we have following styles.

&.checking { background-color: var(--theme-table-bg-hover); }
&.selected { background-color: var(--menu-bg-select); }

Let's use

Comment (agrigorovich-xored) [reply plugins/tracker-resources/src/components/issues/IssuesList.svelte]: Done.

**Review by haiodo — APPROVED** [review]
