### PR TITLE
Workbench fixes

### LINKED ISSUE #1785: Workbench wrong content
1. Open Board
2. Open Card.
3. Switch to Recruit

### PR DESCRIPTION
**Pull request by annano**

### CODE REVIEW

File: plugins/workbench-resources/src/components/Workbench.svelte [hunk 1]
```diff
@@ -123,23 +123,22 @@
...
-          return
+        } else {
+          await updateSpace(currentFolder)
+          setSpaceSpecial(loc.path[3])
         }
       }
 
-      updateSpace(currentFolder)
-      setSpaceSpecial(loc.path[3])
+      await setApp(loc)
```
Comment (BykhovDenis) [inline plugins/workbench-resources/src/components/Workbench.svelte]: Why you move it to down?

Comment (annano) [reply plugins/workbench-resources/src/components/Workbench.svelte]: Moved it back up

**Review by haiodo — APPROVED** [review]
