### PR TITLE
Update UserBoxList layout. Fix AccountPopup.

### LINKED ISSUE #1349: Profile popup is broken
image

### PR DESCRIPTION
**Pull request by SasLord**
(Fixes #1349)

Signed-off-by: Alexander Platov [sas_lord@mail.ru](mailto:sas_lord@mail.ru)

### CODE REVIEW

File: packages/presentation/src/components/UsersPopup.svelte [hunk 1]
```diff
@@ -28,22 +28,32 @@
...
-
-  export let ignoreUsers: Ref<Person>[] = []
+  export let selectedUsers: Ref<Person>[] = []
 
   let search: string = ''
   let objects: Person[] = []
 
   const dispatch = createEventDispatcher()
   const query = createQuery()
-  $: query.query<Person>(_class, { name: { $like: '%' + search + '%' }, _id: { $nin: ignoreUsers } }, result => { objects = result }, { limit: 200 })
```
Comment (haiodo) [inline packages/presentation/src/components/UsersPopup.svelte]: why we miss ignoreUsers?

**Review by haiodo — APPROVED** [review]
