### PR TITLE
QFix: Fix checkbox state

### LINKED ISSUE #7023: `Select All` checkbox wrong behavior
Mess in Select All checkbox state

Original: https://hulycommunity.slack.com/archives/C06DZ5A8TMK/p1729617461613599

image (15)

### PR DESCRIPTION
**Pull request by ArtyomSavchenko**
No selection:
Screenshot 2024-11-20 at 17 50 15

Partial selection:
Screenshot 2024-11-20 at 17 44 26

Full selection:
Screenshot 2024-11-20 at 17 44 19

### CODE REVIEW

File: plugins/view-resources/src/components/Table.svelte [hunk 1]
```diff
@@ -203,6 +203,7 @@
   }
 
   $: checkedSet = new Set<Ref<Doc>>(checked.map((it) => it._id))
+  $: allItemsSelected = objects?.length === checkedSet.size && objects?.length > 0
```
Comment (aonnikov) [inline plugins/view-resources/src/components/Table.svelte:206]: Does object contain all objects or only current "page"? Maybe we should compare with `gtotal` number instead?

**Review by aonnikov — APPROVED** [review]
