### PR TITLE
Fix full text search control behaviour

### LINKED ISSUE #833: Click on comment in table reset search
open object from table also resets search

### PR DESCRIPTION
**Pull request by haiodo**
Fix full text search control behaviour

1. Search after Enter only.
2. Update search on empty value.

Closes #833

Signed-off-by: Andrey Sobolev [haiodo@gmail.com](mailto:haiodo@gmail.com)

### CODE REVIEW

File: packages/ui/src/components/SearchEdit.svelte [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  on:change={() => {
+    if (_search === '') {
+      value = ''
+      dispatch('change', '')
+    }
+  }}
+  on:input={() => {
+    if (_search === '') {
+      value = ''
+      dispatch('change', '')
```
Comment (BykhovDenis) [inline packages/ui/src/components/SearchEdit.svelte:33]: Why we need clear search when input?

Comment (haiodo) [reply packages/ui/src/components/SearchEdit.svelte:33]: input is handled for any change, like copy/paste. And for empty case I've specially added to inform about changes with no waiting for pressing Enter

**Review by BykhovDenis — APPROVED** [review]
