### PR TITLE
UBERF-6537: Fix teamspace creation

### LINKED ISSUE #5353: BUG >> in wiki I cannot create a new workspace (when I select "create" nothing happens)
BUG >> in wiki I cannot create a new workspace (when I select "create" nothing happens)

### PR DESCRIPTION
**Pull request by lexiv0re**
* Fixes new teamspace (and vacancies) creation by re-creating default project types for these modules all the time as they are removed on every upgrade

Related to: https://front.hc.engineering/workbench/platform/tracker/UBERF-6537

Closes: https://github.com/hcengineering/platform/issues/5353

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjFiYzg3MmZiMTljMDhlYWJhZDgwYWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.9-3SJ7wp2Xq6KB1CAw_vc_hY0h8aEgeJ7fLKQel2IfU">Huly&reg;: <b>UBERF-6550</b></a></sub>

### CODE REVIEW

File: models/document/src/migration.ts [hunk 1]
```diff
@@ -314,15 +314,18 @@ export const documentOperation: MigrateOperation = {
...
         state: 'u-default-project',
         func: async (client) => {
-          const tx = new TxOperations(client, core.account.System)
           await createSpace(tx)
-          await createDefaultTeamspaceType(tx)
         }
       }
     ])
+
+    // Currently space type has to be recreated every time as it's in the model
```
Comment (haiodo) [inline models/document/src/migration.ts:327]: You need to move it into model builder in this case.

File: models/lead/src/migration.ts [hunk 2]
```diff
@@ -179,14 +188,17 @@ export const leadOperation: MigrateOperation = {
...
       {
         state: 'u-default-funnel',
-        func: async (client) => {
-          const ops = new TxOperations(client, core.account.System)
+        func: async () => {
           await createDefaults(ops)
         }
       }
     ])
+    // Currently space type has to be recreated every time as it's in the model
```
Comment (haiodo) [inline models/lead/src/migration.ts:200]: And same here and in all other possible places if they exist.

**Review by haiodo — APPROVED** [review]

**Comment by haiodo** [comment]
@lexiv0re I'm merging to fix issues, but let's discuss how to make it better.
