### PR TITLE
fix: missed invite icon

### LINKED ISSUE #4945: Icon for Invite button
<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWYxNjI4ODAwYWY0MjUxMDAxY2JmNWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.r9_jfevvtugXuGd3pidvp0g4z4ek816YcN6Ay9SC0pM">UBERF-5976</a></sub>

### PR DESCRIPTION
**Pull request by euaaaio**
# Contribution checklist

## Brief description

image

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

Resolves #4945

## Contributor requirements

* [ ] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [ ] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

<sub>View in Huly <a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWYyZDk5MTVjODNjZmYzMWIxOWJiNDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.RDTdbxF8bIgQrSEuh_qobhK6WomOwYnB7z4i7VExbJM">UBERF-6004</a></sub>

### CODE REVIEW

File: plugins/login-assets/src/index.ts [hunk 1]
```diff
@@ -1,23 +1,23 @@
...
+import login from '@hcengineering/login'
+import { loadMetadata } from '@hcengineering/platform'
 
-// const icons = require('../assets/icons.svg') as string // eslint-disable-line
-// loadMetadata(login.icon, {
-//   InviteWorkspace: `${icons}#inviteWorkspace`
-// })
+const icons = require('../assets/icons.svg') as string // eslint-disable-line
+loadMetadata(login.icon, {
+  InviteWorkspace: `${icons}#inviteWorkspace`
```
Comment (BykhovDenis) [inline plugins/login-assets/src/index.ts]: May be better move this icon to setting plugin?

Comment (euaaaio) [reply plugins/login-assets/src/index.ts]: Seems like it doesn't matter. But let's do it. It's really used in setting plugin.

**Review by BykhovDenis — APPROVED** [review]
