### PR TITLE
Update StatesBar layout. Fix StyledTextBox.

### LINKED ISSUE #987: Convert StatusBar to monolithic

### LINKED ISSUE #989: Vacancy huge description issue
Putting huge description to Vacancy is rendered incorrectly.

image

### PR DESCRIPTION
**Pull request by SasLord**
(Fixes #987)
(Fixes #989)

### CODE REVIEW

File: plugins/task-resources/src/components/state/StatesBar.svelte [hunk 1]
```diff
@@ -58,7 +64,10 @@
 
   const selectItem = (ev: Event, item: State): void => {
     const el: HTMLElement = ev.currentTarget as HTMLElement
-    el.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' })
+    const rect = el.getBoundingClientRect()
+    const rectScroll = div.getBoundingClientRect()
+    // el.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' })
```
Comment (BykhovDenis) [inline plugins/task-resources/src/components/state/StatesBar.svelte]: Why we need this coomment here?

File: plugins/task-resources/src/components/state/StatesBar.svelte [hunk 2]
```diff
@@ -67,47 +76,46 @@
     dispatch('change')
   }
 
+  const getPosition = (n: number): StatesBarPosition => {
+    if (n === 0) return 'start'
+    else if (n === states.length - 1) return 'end'
+    else return 'middle'
+  }
+
+  const isSafari = (i: number, id: Ref<State>): void => {
```
Comment (BykhovDenis) [inline plugins/task-resources/src/components/state/StatesBar.svelte]: How does the name relate to what it does?

**Review by BykhovDenis — CHANGES_REQUESTED** [review]
Please clean up it

**Review by BykhovDenis — APPROVED** [review]
