### PR TITLE
Move with state and validate

### LINKED ISSUE #616: Support Move for `Tasks`
Now moving Applicaton to another vacancy do not work -- not showing in Kanban. Also move semantic may be different for some classes: e.g. for Applications there should be no other application for same candidate... We need to address this issue somehow

### PR DESCRIPTION
**Pull request by BykhovDenis**
close #616 Signed-off-by: Denis Bykhov [80476319+BykhovDenis@users.noreply.github.com](mailto:80476319+BykhovDenis@users.noreply.github.com)

### CODE REVIEW

File: plugins/recruit-resources/src/components/CreateApplication.svelte [hunk 1]
```diff
@@ -33,17 +34,33 @@
   export let preserveCandidate = false
 
   let status: Status = OK
-  let _space = space
+
+  const doc: Applicant = {
```
Comment (haiodo) [inline plugins/recruit-resources/src/components/CreateApplication.svelte:38]: Why not use AttachedData\<Applicant>?

**Review by aplatoff — APPROVED** [review]
