### PR TITLE
Fixes profile settings copy tooltip truncate

### LINKED ISSUE #4492: Tooltip text for 'Copy' Icon is truncated
Description: When hovering over the 'copy' icon, the tooltip that appears shows truncated text. Instead of displaying "Copy," it shows "Co...," which suggests that the tooltip's container is not wide enough to accommodate the full text.

Steps to Reproduce: Navigate to the Account Settings. Hover over the 'copy' icon. Expected Result: The tooltip should fully display the word "Copy to clipboard" or just "Copy" ("Скопировать в буфер обмена" or "Скопировать" in Russian)

Actual Result: The tooltip shows truncated text as "Co..."

Possible Solution:

* It may be necessary to set a minimum width that can accommodate the text "Copy." This can ensure that the tooltip does not truncate the text.
* If setting a minimum width is not feasible due to design constraints, consider shortening the tooltip text to fit the current container size without truncation.

profile

### PR DESCRIPTION
**Pull request by bogdan-ts**
# Contribution checklist

## Brief description

Fixes #4492 Add min width to text and tooltip text shortened to Copy (Скоприровать) to avoid overflow and fit to text block

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

## Contributor requirements

* [x] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [x] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

File: plugins/contact-resources/src/components/ChannelEditor.svelte [hunk 1]
```diff
@@ -232,6 +232,10 @@
       color: var(--theme-content-color);
       transform: translate(-50%, -50%);
     }
+
+    &.with-tooltip {
+      min-width: 84px;
```
Comment (BykhovDenis) [inline plugins/contact-resources/src/components/ChannelEditor.svelte]: Please use `rem`

Comment (bogdan-ts) [reply plugins/contact-resources/src/components/ChannelEditor.svelte]: > Please use `rem`

fixed

**Review by haiodo — APPROVED** [review]
