### PR TITLE
Fix query update when refresh

### LINKED ISSUE #998: LinkedIn import, attachments not shown
1. Создается Person.
2. Добавляется Mixin (Candidate) => Live query делает Refresh на себя чтобы получить обновленный список кандидатов, он получается 1-2 секунды. Список с lookup, в начале получает на сервере список а потом дополняет их lookup. Тут уже есть кандидат но в нем еще нету на сервере обработанного $inc: attachemnts.
3. Прилетает $inc на attachments(в UI) - объекта еще в списке нету, обновление не проходит.
4. Заканчивает работать (2) и обновляет все без attachments.

### PR DESCRIPTION
**Pull request by BykhovDenis**
close #998 Signed-off-by: Denis Bykhov [80476319+BykhovDenis@users.noreply.github.com](mailto:80476319+BykhovDenis@users.noreply.github.com)

### CODE REVIEW

File: packages/query/src/index.ts [hunk 1]
```diff
@@ -174,7 +178,10 @@ export class LiveQuery extends TxProcessor implements Client {
       } else {
         if (this.getHierarchy().isDerived(tx.mixin, q._class)) {
           // Mixin potentially added to object we doesn't have in out results
-          await this.refresh(q)
+          const doc = await this.findOne(tx.objectClass, { _id: tx.objectId }, q.options)
```
Comment (haiodo) [inline packages/query/src/index.ts]: You need to request, q._class instead, since mixin will not work if not asked.

File: packages/query/src/index.ts [hunk 2]
```diff
@@ -229,14 +236,24 @@ export class LiveQuery extends TxProcessor implements Client {
     const pos = q.result.findIndex((p) => p._id === tx.objectId)
     if (pos !== -1) {
       const updatedDoc = q.result[pos]
-      await this.__updateDoc(q, updatedDoc, tx)
-      if (!this.match(q, updatedDoc)) {
-        q.result.splice(pos, 1)
+      if (updatedDoc.modifiedOn > tx.modifiedOn) return
+      if (updatedDoc.modifiedOn === tx.modifiedOn) {
+        const current = await this.findOne(updatedDoc._class, { _id: updatedDoc._id }, q.options)
```
Comment (haiodo) [inline packages/query/src/index.ts]: Please request q._class, because mixin support should be handled.

**Review by haiodo — CHANGES_REQUESTED** [review]
q._class should be fixed.

**Review by haiodo — APPROVED** [review]
